# Generated by Django 4.2.5 on 2023-09-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                (
                    "call_status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("done", "Done"),
                            ("callback", "Callback"),
                            ("refused", "Refused"),
                        ],
                        default="waiting",
                        max_length=15,
                    ),
                ),
                ("state", models.TextField(blank=True, null=True)),
                ("place", models.TextField(blank=True, null=True)),
                ("date_distribution", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Male"), ("female", "Female")],
                        max_length=6,
                        null=True,
                    ),
                ),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("volunteer", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("items_received", models.ManyToManyField(to="call_manager.item")),
            ],
        ),
    ]
