# Generated by Django 4.2.5 on 2023-09-12 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("call_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipient",
            name="last_updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_recipients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
