# Generated by Django 4.2.5 on 2023-09-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("call_manager", "0002_recipient_last_updated_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipient",
            name="call_status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting"),
                    ("done", "Done"),
                    ("refused", "Refused"),
                    ("invalid", "Invalid Number"),
                ],
                default="waiting",
                max_length=15,
            ),
        ),
    ]
