# Generated by Django 4.2.5 on 2023-09-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("call_manager", "0003_alter_recipient_call_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipient",
            name="call_back_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="call_status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting"),
                    ("done", "Done"),
                    ("refused", "Refused"),
                    ("invalid", "Invalid Number"),
                    ("call_back", "Call Back"),
                ],
                default="waiting",
                max_length=15,
            ),
        ),
    ]
