# Generated by Django 4.2.5 on 2023-09-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("call_manager", "0005_recipient_last_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipient",
            name="done_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
