# Generated by Django 4.2.5 on 2023-09-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="call_back_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
